
package org.jaxws.bottom.up.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeService", targetNamespace = "http://up.bottom.jaxws.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeService {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.jaxws.bottom.up.client.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployee", targetNamespace = "http://up.bottom.jaxws.org/", className = "org.jaxws.bottom.up.client.GetEmployee")
    @ResponseWrapper(localName = "getEmployeeResponse", targetNamespace = "http://up.bottom.jaxws.org/", className = "org.jaxws.bottom.up.client.GetEmployeeResponse")
    @Action(input = "http://up.bottom.jaxws.org/EmployeeService/getEmployeeRequest", output = "http://up.bottom.jaxws.org/EmployeeService/getEmployeeResponse")
    public Employee getEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.jaxws.bottom.up.client.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEmployee", targetNamespace = "http://up.bottom.jaxws.org/", className = "org.jaxws.bottom.up.client.AddEmployee")
    @ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://up.bottom.jaxws.org/", className = "org.jaxws.bottom.up.client.AddEmployeeResponse")
    @Action(input = "http://up.bottom.jaxws.org/EmployeeService/addEmployeeRequest", output = "http://up.bottom.jaxws.org/EmployeeService/addEmployeeResponse")
    public Employee addEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteEmployee", targetNamespace = "http://up.bottom.jaxws.org/", className = "org.jaxws.bottom.up.client.DeleteEmployee")
    @ResponseWrapper(localName = "deleteEmployeeResponse", targetNamespace = "http://up.bottom.jaxws.org/", className = "org.jaxws.bottom.up.client.DeleteEmployeeResponse")
    @Action(input = "http://up.bottom.jaxws.org/EmployeeService/deleteEmployeeRequest", output = "http://up.bottom.jaxws.org/EmployeeService/deleteEmployeeResponse")
    public boolean deleteEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.jaxws.bottom.up.client.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateEmployee", targetNamespace = "http://up.bottom.jaxws.org/", className = "org.jaxws.bottom.up.client.UpdateEmployee")
    @ResponseWrapper(localName = "updateEmployeeResponse", targetNamespace = "http://up.bottom.jaxws.org/", className = "org.jaxws.bottom.up.client.UpdateEmployeeResponse")
    @Action(input = "http://up.bottom.jaxws.org/EmployeeService/updateEmployeeRequest", output = "http://up.bottom.jaxws.org/EmployeeService/updateEmployeeResponse")
    public Employee updateEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
