
package org.jaxws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SOAPI", targetNamespace = "http://soap.jaxws.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SOAPI {


    /**
     * 
     * @return
     *     returns java.util.List<org.jaxws.soap.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://soap.jaxws.org/", className = "org.jaxws.soap.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://soap.jaxws.org/", className = "org.jaxws.soap.GetUsersResponse")
    @Action(input = "http://soap.jaxws.org/SOAPI/getUsersRequest", output = "http://soap.jaxws.org/SOAPI/getUsersResponse")
    public List<User> getUsers();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addUser", targetNamespace = "http://soap.jaxws.org/", className = "org.jaxws.soap.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://soap.jaxws.org/", className = "org.jaxws.soap.AddUserResponse")
    @Action(input = "http://soap.jaxws.org/SOAPI/addUserRequest", output = "http://soap.jaxws.org/SOAPI/addUserResponse")
    public void addUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

}
